---

- name: regenerate locales
  shell: locale-gen && update-locale "LANG=en_US.UTF-8"

- name: update debian certificates
  command: update-ca-certificates

- name: update rhel certificates
  command: update-ca-trust

- name: reload ssh
  service:
    name:  "{{ ssh_service }}"
    state: restarted

- name: restart atop
  service:
    name:  atop
    state: restarted

- name: reload hostname RedHat
  command: "hostnamectl set-hostname {{ hostname }}"

- name: reload hostname Debian
  service:
    name: hostname
    state: restarted

- name: reload NetworkManager
  service:
    name: NetworkManager
    state: reloaded
